# Generated by Django 4.0.3 on 2022-04-01 13:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages', verbose_name='Imagen')),
            ],
        ),
    ]
