# Generated by Django 4.0.3 on 2022-04-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
    ]
