# Generated by Django 4.0.3 on 2022-04-12 19:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=150, verbose_name='Receta')),
                ('ingredients', ckeditor.fields.RichTextField(verbose_name='Ingredientes')),
                ('preparation', ckeditor.fields.RichTextField(verbose_name='Preparación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Foto')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
